docs/plugins.md
lib/classes/process.js
package.json

```
[x] Bugfix
[ ] Feature
[x] Update dependencies
```
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the impact and migration path for existing applications:

fix(executors): duplicate call to notification fail

---

api/api.js
lib/classes/execution.js
lib/classes/process.js
package.json

api: removed old direct process SIGKILL
execution: reformat execMain and killMain methods
process: changes to method calls
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(api): fix to make the chain end when kill a process from api

---

docs/api_es.md

```
[ ] Bugfix
[ ] Feature
[X] Documentation
```
```
[ ] Yes
[ ] No
```

docs(api): create spanish API WS doc

---

docs/api_es.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation
```
```
[ ] Yes
[ ] No
```

docs(api): fix spanish API WS doc

---

docs/api_es.md
lib/config/defaults.json
lib/utils.js
samples/conf.json
samples/config_simple.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(core): Not need "config" object in config file

---

lib/classes/process.js
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat(executors): new output db global values countRows

---

package.json

rename app.js to index.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build(core): fix package bin file

---

api/api.js
lib/classes/chain.js
lib/classes/execution.js
lib/classes/process.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fix outputshare

---

lib/classes/execution.js
package.json

return execute_db_countRows from execution end to process values
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

fix(executor): return execute_db_countRows

---

lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(executor): add conditions "<" and ">"

---

lib/classes/chain.js
lib/classes/plan.js
lib/classes/process.js
lib/schemas/process.json
lib/utils.js
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(core): new feat depends_conditions

---

lib/classes/chain.js
lib/classes/process.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

bug: fix depends_conditions and global_values bugs

---

lib/classes/chain.js
lib/classes/process.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: end chains when some proc is ignored

---

lib/classes/event.js
lib/utils.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(executors): error catch

---

lib/classes/event.js
lib/classes/plan.js
lib/classes/process.js
lib/utils.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Fix custom values

---

docs/chains.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation
```
```
[ ] Yes
[ ] No
```

docs(core): custom_values (chain)

---

lib/classes/chain.js
lib/classes/process.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): crash when custom_values not set in chain

---

lib/classes/chain.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): custom values bug

---

lib/classes/process.js
lib/utils.js
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): sensitive-case global values

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
lib/schemas/conf.json
lib/utils.js
package.json

```
[ ] Bugfix
[x] Feature
```
closes #33 
```
[ ] Yes
[ ] No
```

feat(core): Enable in configuration(history/mongodb) field database

---

docs/conf.md
lib/classes/chain.js
lib/classes/plan.js
lib/classes/process.js
lib/utils.js
package.json
samples/plan_deps_advanced.json
samples/plan_standard.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

refactor(core): utils replaceWith and addGlobalValuesToObjParams

---

lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
Changes on schemas of executors and notificators:
- Migrate schemas from v4 to v6: ajv-cli migrate -s schema.json
- pattern must replace "@runnerty/" by "@runnerty-"
Change configs (conf.json) to set type replace "@runnerty/" by "@runnerty-".

fix(core): schema validator

---

lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): error when module (executor/notificator) not exists

---

lib/classes/execution.js
lib/classes/process.js
lib/schemas/process.json
lib/utils.js
package.json

```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): retries and replaces fixs

---

lib/classes/notification.js
lib/queue-notifications-memory.js
lib/queue-notifications-redis.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): new notificators method end

---

lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): mongoose.connect deprecated

---

package.json
samples/conf.json
samples/config_simple.json
samples/etc_runnerty/package.json

```
[ ] Bugfix
[ ] Feature
[x] Samples
```
```
[ ] Yes
[ ] No
```

docs(core): update samples

---

lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): schema validation on windows

---

lib/classes/execution.js
lib/classes/process.js
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: executors output refactor

---

lib/classes/process.js
lib/mongodb-models/process.js
lib/utils.js
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feature: historize process output-size

---

lib/app.js
lib/utils.js
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feature: new command to set memory limit

---

lib/classes/chain.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: async error evaluating depends conditions

---

lib/classes/chain.js
lib/classes/notificationEvent.js
lib/classes/process.js
lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(core): noifications issues

---

docs/chains.md

```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: **docs**
```
```
[ ] Yes
[x] No
```

docs: chains docs corrections

---

lib/classes/process.js
lib/utils.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(core): replace output_share not resolved values by ""

---

docs/process.md
docs/values.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: docs
```
```
[ ] Yes
[x] No
```

docs: add values documentatio

---

docs/values.md
lib/utils.js
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: get environment variables

---

lib/classes/execution.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: executors replace params

---

lib/app.js
lib/classes/chain.js
lib/classes/execution.js
lib/classes/filePlan.js
lib/classes/notification.js
lib/classes/plan.js
lib/classes/process.js
lib/depends-process.js
lib/init.js
lib/utils.js
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor: refactor var const let

---

docs/chains.md
docs/conf.md
docs/dependencies.md
docs/executors.md
docs/notificators.md
docs/plan.md
docs/process.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add docs
```
```
[ ] Yes
[x] No
```

docs: add dependencies doc

---

lib/classes/notification.js
lib/classes/process.js
lib/utils.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: notification promise end process

---

README.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: add contributors

---

lib/schemas/config.json
package.json
ws-api/ws-api.js

```
[ ] Bugfix
[x] Feature
```
**What is the current behavior?**
Before, your local Runnerty API only listened to http
Now you can set up the local Runnerty private API to listen http, https and unix socket. Also some refactor all along the webservice API and ES6
```
[ ] Yes
[x] No
```
**Other …

refactor(ws-api): ES6, improvements & config.json scheme

---

.all-contributorsrc
README.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

All contributors file

---

lib/classes/process.js

closes #77
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: Process never ends when don´t have on_end notification

---

lib/config/defaults.json
ws-api/ws-api.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Bugfix ws-api: bypassed 401 and default log level

---

package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 1.0.1

---

docs/values.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Fix docs
```
```
[ ] Yes
[x] No
```

docs: fix values doc

---

docs/usage.md
lib/app.js
lib/config/defaults.json
lib/init.js
lib/utils.js
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: force chain executions on init

---

lib/classes/chain.js
lib/classes/process.js
lib/config/defaults.json
lib/utils.js
package.json
samples/config.json
samples/etc_runnerty/package.json

- Remove unnecessary escape char into regexps
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: typo humnized to humanized and WSAPI promise resolve without API config

---

lib/classes/chain.js
lib/depends-process.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: depends_process is not replacing values with custom_values

---

docs/api.md
docs/chains.md
docs/config.md
docs/dependencies.md
docs/executors.md
docs/notificators.md
docs/plan.md
docs/plugins.md
docs/process.md
docs/triggers.md
docs/values.md
samples/config.json
samples/plan_deps_advanced.json
samples/plan_simple.json
samples/plan_standard.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: triggers docs ans samples

---

lib/interpreter-functions.js
lib/queue-notifications-memory.js
lib/queue-notifications-redis.js
package.json
ws-api/ws-api.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: typo and replace interpreter function

---

lib/classes/chain.js
lib/classes/plan.js
lib/classes/queueSubscription.js
lib/classes/trigger.js
lib/interpreter.js
lib/queue-process-memory.js
lib/utils.js
package.json

- [] Docs have been added / updated (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: inaccessible trigger output

---

docs/functions.md
lib/interpreter-functions.js
lib/interpreter.js
lib/utils.js
package.json

```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

fix: resolution of GetValue functions as values

---

CHANGELOG.md
docs/functions.md
lib/interpreter-functions.js

```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[X] No
```

feat: interpreter JSON stringify function

---

docs/functions.md
lib/classes/plan.js
lib/interpreter-functions.js
lib/utils.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: replaceWithSmart ignore global_values when objParams is empty

---

lib/classes/process.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: output_share issue: overwriting config.global_values instead of raw

---

docs/chains.md
docs/config.md
docs/plugins.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Improve documentation
```
```
[ ] Yes
[x] No
```

feat(docs): Improvements and new functionalities documentation

---

lib/classes/trigger.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: input trigger

---

docs/api.md
docs/api_es.md
ws-api/ws-api.js

closes #123
```
[ ] Bugfix
[x] Feature
```
Now you can ckeck if the runnerty instance is running. 
You can call /api/health and it will return an http 200.
```
[ ] Yes
[x] No
```

feat: add health checker endpoint

---

CHANGELOG.md
docs/plan.md
lib/classes/filePlan.js
lib/init.js
lib/schemas/config.json
lib/utils.js
package-lock.json
package.json

feat: standard Node.js module resolution paths
feat: it is possible to indicate the plan object in config.json
```
[ ] Bugfix
[x] Feature
```
feat: standard Node.js module resolution paths
feat: it is possible to indicate the plan object in config.json
```
[ ] Yes
[x] No
```
If this PR contains a breaking change, please describe the …

build: 2.4.0

---

lib/classes/process.js
lib/classes/runnertyio.js
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.4.0-rc.6

---

__tests__/end2end.spec.js
__tests__/end2end/plan_check_iter_end_error.json
__tests__/end2end/plan_check_iter_end_ok.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: tests
```
```
[ ] Yes
[x] No
```

test: check iterable end error and ok

---

__tests__/end2end/config.json
lib/app.js
lib/classes/runnertyio.js
lib/init.js
package-lock.json
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feature: telemetry send version on access

---

__tests__/end2end/package-lock.json
lib/classes/chain.js
lib/classes/process.js
lib/depends-process.js
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: complex prod depen. could cause double exec

---

docs/api.md
docs/api_es.md
docs/chains.md
docs/config.md
docs/dependencies.md
docs/executors.md
docs/functions.md
docs/notifiers.md
docs/plugins.md
docs/process.md
docs/queues.md
docs/usage.md
docs/values.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation
```
```
[ ] Yes
[x] No
```

chore(docs): update docs for 2.5.0

---

.eslintrc.json
CHANGELOG.md
__tests__/utils.spec.js
lib/app.js
lib/classes/chain.js
lib/classes/execution.js
lib/classes/filePlan.js
lib/classes/notification.js
lib/classes/notificationEvent.js
lib/classes/plan.js
lib/classes/process.js
lib/classes/queueSubscription.js
lib/classes/runnertyio.js
lib/classes/trigger.js
lib/config/defaults.json
lib/depends-process.js
lib/init.js
lib/interpreter-functions.js
lib/interpreter.js
lib/queue-notifications-memory.js
lib/queue-notifications-redis.js
lib/queue-process-memory.js
lib/queues.js
lib/schemas/config.json
lib/utils.js
package-lock.json
package.json
samples/plan_standard.json
ws-api/ws-api.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.6.2

---

package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.6.3

---

.eslintignore
.prettierignore
CHANGELOG.md
__tests__/end2end/plan_link.json
__tests__/end2end/plan_link_chain_sample.json
lib/classes/chain.js
lib/classes/filePlan.js
lib/classes/plan.js
lib/classes/queueSubscription.js
lib/init.js
lib/utils.js
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.6.4

---

CHANGELOG.md
lib/classes/process.js
package-lock.json
package.json

```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

build: 2.6.5

---

CHANGELOG.md
lib/classes/plan.js
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: api remote chain execution

---

CHANGELOG.md
docs/triggers.md
lib/classes/chain.js
lib/classes/execution.js
lib/classes/notification.js
lib/classes/process.js
lib/classes/trigger.js
lib/config/defaults.json
lib/depends-process.js
lib/schemas/config.json
lib/utils.js
package-lock.json
package.json
ws-api/ws-api.js

```
[] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

build: 2.7.0-rc3

---

lib/classes/notification.js
package-lock.json
package.json
ws-api/ws-api.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.7.0-rc4

---

CHANGELOG.md
__tests__/end2end.spec.js
__tests__/end2end/plan_parallel_error.json
lib/classes/chain.js
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.7.0-rc5

---

CHANGELOG.md
package-lock.json
package.json

```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

build: 2.7.0

---

CHANGELOG.md
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.8.0

---

CHANGELOG.md
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 2.8.2

---

CHANGELOG.md
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: dependency security updates
```
```
[ ] Yes
[x] No
```

features: minor dependency updates

---

CHANGELOG.md
__tests__/end2end/config.json
__tests__/end2end/plan_args_custom-values.json
__tests__/end2end/plan_check_iter_end_error.json
__tests__/end2end/plan_check_iter_end_ok.json
__tests__/end2end/plan_complex_dependencies.json
__tests__/end2end/plan_defaults_processes.json
__tests__/end2end/plan_link.json
__tests__/end2end/plan_link_chain_sample.json
__tests__/end2end/plan_parallel_error.json
__tests__/end2end/plan_queue.json
__tests__/end2end/plan_retry.json
__tests__/end2end/plan_retry_caof_obj.json
__tests__/end2end/plan_simple_iter.json
__tests__/end2end/plan_simple_iter_fail.json
__tests__/end2end/plan_simple_iter_fail_not_end.json
lib/classes/chain.js
lib/schemas/chain.json
package-lock.json
package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat: input strings array

---

__tests__/end2end/config.json
__tests__/end2end/package.json
lib/classes/runnertyio.js
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: 3.0.0-rc1

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/CI.yml
CHANGELOG.md
CONTRIBUTING.md
lib/classes/filePlan.js
lib/init.js
package-lock.json
package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 3.0.2

---

CHANGELOG.md
package-lock.json
package.json
ws-api/ws-api.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build: 3.2.3

---

CHANGELOG.md
package-lock.json
package.json
ws-api/ws-api.js

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

release: 3.4.1

---

CHANGELOG.md
lib/schemas/config.json
package-lock.json
package.json
ws-api/ws-api.js

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

release: 3.4.2

---

CHANGELOG.md
__tests__/end2end.spec.js
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
```
[ ] Yes
[X] No
```

release: 3.4.4
